--drop table "HR"."STUDENT";
CREATE TABLE "HR"."STUDENT"
   (	"id" NUMBER(19,0),
	    "name" VARCHAR2(4000 BYTE)
   ) ;

--drop SEQUENCE  "HR"."STUDENT_SEQ";
CREATE SEQUENCE  "HR"."STUDENT_SEQ"  START WITH 1 INCREMENT BY 1 NOMAXVALUE CACHE 1000;